replicaCount: 2

existingSecret: django-app-secrets

image:
  repository: 487337210313.dkr.ecr.eu-central-1.amazonaws.com/final-project-ecr
  tag: "v1.0.4"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  host: django.example.com
  path: /
  pathType: Prefix
  tls: false

config:
  ALLOWED_HOSTS: "localhost,127.0.0.1,.elb.amazonaws.com,django-app-django,django-app-django.django.svc,django-app-django.django.svc.cluster.local"
  DEBUG: "False"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
